###############################################################################
#
# Makefile to study the relation between income group of a country and its GDP 
#
# License: GPL (General Public License)
# Authors: Charles McCann
#          Dominique Edwards
#          Hari Sanadhya
#          Huynh vu
# Date:    2017/03/19
# 
# Description:
# ------------
# The purpose of this makefile is to provide all the steps to regenerate the study aimed to find relationship 
#  between the income group of a country with its GDP value.
# 
# Usage:
# ------
# 1. Copy the Makefile to your program directory.
# 2. Type make to start building your program.
#
# Make Target:
# ------------
# The Makefile provides the following targets to make:
#   $ make								compile and link
#   $ make clean					removes all the files that will be created by this process
#   $ make download				downloads the raw GDP data and educational statistics data file from the internet
#   $ make tidy_edu				cleans/tidies the raw educational file and stores the tidy file in the data folder
#   $ make tidy_gdp				cleans/tidies the raw GDP file and stores the tidy file in the data folder
#   $ make report.md			using the tidied education and GDP data, perform certain data analytics process to 
#														analyze relationship between GDP and income group.
#   $ make all						Perfrom all the above make targets with a single command execution

all: clean download tidy_edu tidy_gdp report.md

# remove all the files generated by this process
clean:
	rm -f data/gdp.csv data/edu.csv report.md data/cleaned_EDU_Data.txt data/cleaned_GDP_Data.txt data/merged_Data.txt graphs/CountryCode_vs_GDP.png graphs/Modified CountryCode_vs_GDP.png

# Download the raw GDP and EDU data from internet and save it in data folder by the names gdp.csv and edu.csv
download:
	Rscript -e 'download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", destfile = "data/gdp.csv", method="auto", quiet = TRUE)'
	Rscript -e 'download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv", destfile = "data/edu.csv", method="auto", quiet = TRUE)'

# Call the r script that will generate tidy EDU data file - data/cleaned_EDU_Data.txt
tidy_edu: source/EDU_data.R
	Rscript $<

# Call the r script that will generate tidy GDP data file - data/cleaned_GDP_Data.txt
tidy_gdp: source/GDP_data.r
	Rscript $<

# Call the r script that will use the data analytics tools to analyze the GDP and the EDU data to determine
# the realtionship between GDP and Income group of a country.
report.md: report.Rmd 
	Rscript -e 'find.package("rmarkdown")'
	Rscript -e 'rmarkdown::render("$<")'
